version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: product-postgres
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

volumes:
  product_data: